game.name = Frantic^-1
game.command = java -jar not-frantic.jar client
game.description.file = website/index.html
game.screenshot.file = screenshot.png
game.server.command = java -jar not-frantic.jar server
game.use = true
game.year = 2026
game.developers = Aiysha Mei Frutiger, Denys Verich, Senanur Ates, Sevval Ünlü