image: eclipse-temurin:25-jdk

stages:
  - test
  - build

pipeline-test:
  stage: test
  timeout: 10m
  script:
    - chmod +x gradlew
    - ./gradlew --no-daemon clean pipelineTest --stacktrace
  artifacts:
    when: always
    reports:
      junit: build/test-results/pipelineTest/*.xml
    paths:
      - build/reports/tests/pipelineTest/

build-jar:
  stage: build
  timeout: 10m
  script:
    - chmod +x gradlew
    - ./gradlew --no-daemon fatJar
  artifacts:
    when: always
    paths:
      - build/libs/